### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal (exchangeDevice at /pytorch/c10/cuda/impl/CUDAGuardImpl.h:29)

### ISSUE THREAD

**Issue by OlivierX** [D-X-Y/landmark-detection#29]
Error occurs while running training programme "bash scripts/300W/300W_CYCLE_128.sh 0 GTB". It has only one GPU so i set CUDA device to 0 but it still makes error.

**Comment by OlivierX** [comment]
==>>[2019-07-23 11:45:01] Epoch[001/201], [Time Left: 00:00:00]
Traceback (most recent call last):
  File "san_main.py", line 115, in <module>
    main()
  File "san_main.py", line 105, in main
    args.cycle_model_path = procedure.train_cycle_gan(cycledata, itnetwork, args, log)
  File "/home/liux/Github/landmark-detection-master/SAN/lib/procedure/train_cycle.py", line 64, in train_cycle_gan
    model.optimize_parameters()
  File "/home/liux/Github/landmark-detection-master/SAN/lib/models/itn.py", line 175, in optimize_parameters
    self.backward_G()
  File "/home/liux/Github/landmark-detection-master/SAN/lib/models/itn.py", line 154, in backward_G
    pred_fake = self.netD_A.forward(self.fake_B)
  File "/home/liux/Github/landmark-detection-master/SAN/lib/models/discriminator_model.py", line 46, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "/home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 202, in data_parallel
    inputs, module_kwargs = scatter_kwargs(inputs, module_kwargs, device_ids, dim)
  File "/home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/cuda/comm.py", line 147, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error: invalid device ordinal (exchangeDevice at /pytorch/c10/cuda/impl/CUDAGuardImpl.h:29)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fcaebaaa441 in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fcaebaa9d7a in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0xb814 (0x7fcae4b02814 in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: at::CUDAType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const + 0x135 (0x7fca9b7c4695 in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #4: torch::autograd::VariableType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const + 0x284 (0x7fca8f07c094 in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #5: at::native::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) + 0x506 (0x7fca908eb666 in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #6: at::TypeDefault::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const + 0x17 (0x7fca90b6a857 in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #7: torch::autograd::VariableType::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const + 0x2c2 (0x7fca8ef65b52 in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #8: torch::cuda::scatter(at::Tensor const&, c10::ArrayRef<long>, c10::optional<std::vector<long, std::allocator<long> > > const&, long, c10::optional<std::vector<c10::optional<c10::cuda::CUDAStream>, std::allocator<c10::optional<c10::cuda::CUDAStream> > > > const&) + 0x389 (0x7fca8f4b9fd9 in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #9: <unknown function> + 0x5a27bf (0x7fcaec4a47bf in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x130cfc (0x7fcaec032cfc in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #21: THPFunction_apply(_object*, _object*) + 0x6b1 (0x7fcaec2b5481 in /home/liux/.conda/envs/vp36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)

Here is the error information.

**Comment by D-X-Y** [comment]
I did not have this error when running on my machine. Maybe you could check your machine, python, pytorch version?

**Comment by OlivierX** [comment]
Thx,  I've solved it. It turns out to be the problem of the doublicate definition of parameters in the script. So I've reinstalled my driver and cuda for nothing ... c'est la vie :)
