### ISSUE TITLE
Evaluating the 300W using the pre-trained model on cpu

### ISSUE THREAD

**Issue by MANGA-1614** [D-X-Y/landmark-detection#53]
Hello,

Thank you so much for your code and paper. I'm working on evaluating the pre-trained model you provided on the 300W dataset. However, I don't have GPU, so I can't use CUDA. 
`AssertionError: Torch not compiled with CUDA enabled`

I found this part here in evaluate_detector.py:
`target = target.cuda()
    mask = mask.cuda()`

I've already edited the code in train_detector.py to take the CPU:
`torch.load(opt.resume, map_location=torch.device('cpu'))`

I've also edited the 300W-EVAL.sh file to do no GPUs through:
`--gpu_ids -1`

I can evaluate on single images, but I'd like to get an NME myself by evaluating the dataset.

I'm not sure how to proceed from here. If this is possible, please let me know.

Thank you very much for your time.

Sincerely,
John

**Comment by D-X-Y** [comment]
which project are you using?

**Comment by MANGA-1614** [comment]
I'm working on the SAN.

**Comment by D-X-Y** [comment]
If you are using `san_eval.py` to evaluate the model, you can use `--cpu` augment to evaluate on CPU following https://github.com/D-X-Y/landmark-detection/tree/master/SAN#evaluation-on-the-single-image. If you want to evaluate on the whole 300W test set, you should use this file `san_main.py`. If so, some codes should be modified.

**Comment by MANGA-1614** [comment]
Yea, I got the san-eval.py to work on the cpu. I'll try looking at where in
the san_main.py to edit.

**Comment by MANGA-1614** [comment]
I finally got it to work. I didn't edit san_main.py, but changed evaluate_detector.py instead. I commented out:

```
target = target.duda()
mask = mask.cuda()
```

**Comment by D-X-Y** [comment]
Nice!
